const mongoose = require('mongoose');

// 1. Schema for the diagnostic questions generated by AI
const questionSchema = new mongoose.Schema({
  question_id: { 
    type: Number, 
    required: true 
  },
  text: { 
    type: String, 
    required: true 
  },
  options: {
    type: [String],
    required: true,
    validate: {
      validator: function(v) {
        return v.length === 4;
      },
      message: "Each question must have exactly 4 multiple-choice options."
    }
  },
  correct_option: {
    type: String,
    required: true
  },
  reasoning_prompt: {
    type: String,
    default: null
  },
  target_topics: [{ 
    type: String,
    required: true
  }]
}, { _id: false });

// 2. Schema for the user's submitted answers
const answerSchema = new mongoose.Schema({
  question_id: { 
    type: Number, 
    required: true 
  },
  answer_text: { 
    type: String, 
    default: "" 
  }
}, { _id: false });

// 3. Schema for the AI's subtopic evaluations
const evaluationSchema = new mongoose.Schema({
  subtopic_name: { 
    type: String, 
    required: true 
  },
  remarks: { 
    type: String, 
    required: true 
  },
  retention: { 
    type: String, 
    enum: ['red', 'yellow', 'green'], 
    required: true 
  }
}, { _id: false });

// 4. Main Test Schema
const testSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  subject: {
    type: String,
    required: true,
    trim: true,
    index: true
  },
  status: {
    type: String,
    enum: ['pending', 'graded', 'abandoned'],
    default: 'pending',
    index: true
  },
  questions: {
    type: [questionSchema],
    required: true
  },
  answers: {
    type: [answerSchema],
    default: []
  },
  evaluations: {
    type: [evaluationSchema],
    default: []
  }
}, {
  timestamps: true // Automatically generates createdAt and updatedAt fields
});

// Compound Index: Speeds up querying pending tests by User + Subject
testSchema.index({ user: 1, subject: 1, status: 1 });

const Test = mongoose.model('Test', testSchema);

module.exports = Test;